# Generated by Django 5.0.1 on 2024-01-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=75)),
                ('from_wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_wallet', to='wallet.wallet')),
                ('to_wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destintaion_wallet', to='wallet.wallet')),
            ],
        ),
    ]
